"""Add EmailVerificationCode

Revision ID: 0957423bbcec
Revises: 007
Create Date: 2026-06-16 13:55:24.529735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0957423bbcec'
down_revision: Union[str, None] = '007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_codes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_codes_user_id'), 'email_verification_codes', ['user_id'], unique=False)
    op.drop_table('subscription_tier_limits')
    op.drop_table('usage_counters')
    op.drop_constraint(op.f('auth_token_deny_list_jti_key'), 'auth_token_deny_list', type_='unique')
    op.drop_index(op.f('ix_auth_token_deny_list_jti'), table_name='auth_token_deny_list')
    op.create_index(op.f('ix_auth_token_deny_list_jti'), 'auth_token_deny_list', ['jti'], unique=True)
    op.drop_constraint(op.f('buyers_project_id_fkey'), 'buyers', type_='foreignkey')
    op.drop_constraint(op.f('developers_user_id_key'), 'developers', type_='unique')
    op.drop_index(op.f('ix_developers_user_id'), table_name='developers')
    op.create_index(op.f('ix_developers_user_id'), 'developers', ['user_id'], unique=True)
    op.drop_constraint(op.f('developers_user_id_fkey'), 'developers', type_='foreignkey')
    op.drop_index(op.f('idx_inquiries_developer'), table_name='inquiries')
    op.drop_index(op.f('idx_inquiries_unseen'), table_name='inquiries', postgresql_where='(seen_by_developer = false)')
    op.drop_index(op.f('uq_inquiry_project_email'), table_name='inquiries')
    op.create_index(op.f('ix_inquiries_developer_id'), 'inquiries', ['developer_id'], unique=False)
    op.create_index(op.f('ix_inquiries_email'), 'inquiries', ['email'], unique=False)
    op.create_index(op.f('ix_inquiries_project_id'), 'inquiries', ['project_id'], unique=False)
    op.drop_index(op.f('ix_milestone_approvals_milestone'), table_name='milestone_approvals')
    op.drop_constraint(op.f('milestones_project_id_fkey'), 'milestones', type_='foreignkey')
    op.create_index(op.f('ix_notification_log_developer_id'), 'notification_log', ['developer_id'], unique=False)
    op.drop_constraint(op.f('password_reset_tokens_token_hash_key'), 'password_reset_tokens', type_='unique')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.drop_index(op.f('ix_permissions_resource_action'), table_name='permissions')
    op.drop_constraint(op.f('photos_upload_id_fkey'), 'photos', type_='foreignkey')
    op.drop_constraint(op.f('projects_project_code_key'), 'projects', type_='unique')
    op.drop_index(op.f('uq_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_code'), table_name='projects')
    op.create_index(op.f('ix_projects_project_code'), 'projects', ['project_code'], unique=True)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.drop_constraint(op.f('projects_developer_id_fkey'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('uploads_idempotency_key_key'), 'uploads', type_='unique')
    op.drop_index(op.f('ix_uploads_idempotency_key'), table_name='uploads')
    op.create_index(op.f('ix_uploads_idempotency_key'), 'uploads', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_uploads_milestone_id'), 'uploads', ['milestone_id'], unique=False)
    op.drop_constraint(op.f('uploads_developer_id_fkey'), 'uploads', type_='foreignkey')
    op.drop_constraint(op.f('uploads_project_id_fkey'), 'uploads', type_='foreignkey')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('idx_vpv_country'), table_name='visibility_page_views')
    op.drop_index(op.f('idx_vpv_project_time'), table_name='visibility_page_views')
    op.create_index(op.f('ix_visibility_page_views_project_id'), 'visibility_page_views', ['project_id'], unique=False)
    op.drop_constraint(op.f('webhook_events_event_id_key'), 'webhook_events', type_='unique')
    op.drop_index(op.f('ix_webhook_events_event_id'), table_name='webhook_events')
    op.create_index(op.f('ix_webhook_events_event_id'), 'webhook_events', ['event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_events_event_id'), table_name='webhook_events')
    op.create_index(op.f('ix_webhook_events_event_id'), 'webhook_events', ['event_id'], unique=False)
    op.create_unique_constraint(op.f('webhook_events_event_id_key'), 'webhook_events', ['event_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_visibility_page_views_project_id'), table_name='visibility_page_views')
    op.create_index(op.f('idx_vpv_project_time'), 'visibility_page_views', ['project_id', sa.literal_column('viewed_at DESC')], unique=False)
    op.create_index(op.f('idx_vpv_country'), 'visibility_page_views', ['project_id', 'country_code'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key(op.f('uploads_project_id_fkey'), 'uploads', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('uploads_developer_id_fkey'), 'uploads', 'developers', ['developer_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_uploads_milestone_id'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_idempotency_key'), table_name='uploads')
    op.create_index(op.f('ix_uploads_idempotency_key'), 'uploads', ['idempotency_key'], unique=False)
    op.create_unique_constraint(op.f('uploads_idempotency_key_key'), 'uploads', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key(op.f('projects_developer_id_fkey'), 'projects', 'developers', ['developer_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_code'), table_name='projects')
    op.create_index(op.f('ix_projects_project_code'), 'projects', ['project_code'], unique=False)
    op.create_index(op.f('uq_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_unique_constraint(op.f('projects_project_code_key'), 'projects', ['project_code'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key(op.f('photos_upload_id_fkey'), 'photos', 'uploads', ['upload_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_permissions_resource_action'), 'permissions', ['resource', 'action'], unique=False)
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=False)
    op.create_unique_constraint(op.f('password_reset_tokens_token_hash_key'), 'password_reset_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_notification_log_developer_id'), table_name='notification_log')
    op.create_foreign_key(op.f('milestones_project_id_fkey'), 'milestones', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_milestone_approvals_milestone'), 'milestone_approvals', ['milestone_id'], unique=False)
    op.drop_index(op.f('ix_inquiries_project_id'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_email'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_developer_id'), table_name='inquiries')
    op.create_index(op.f('uq_inquiry_project_email'), 'inquiries', ['project_id', 'email'], unique=True)
    op.create_index(op.f('idx_inquiries_unseen'), 'inquiries', ['project_id'], unique=False, postgresql_where='(seen_by_developer = false)')
    op.create_index(op.f('idx_inquiries_developer'), 'inquiries', ['developer_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_foreign_key(op.f('developers_user_id_fkey'), 'developers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_developers_user_id'), table_name='developers')
    op.create_index(op.f('ix_developers_user_id'), 'developers', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('developers_user_id_key'), 'developers', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key(op.f('buyers_project_id_fkey'), 'buyers', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_auth_token_deny_list_jti'), table_name='auth_token_deny_list')
    op.create_index(op.f('ix_auth_token_deny_list_jti'), 'auth_token_deny_list', ['jti'], unique=False)
    op.create_unique_constraint(op.f('auth_token_deny_list_jti_key'), 'auth_token_deny_list', ['jti'], postgresql_nulls_not_distinct=False)
    op.create_table('usage_counters',
    sa.Column('developer_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('billing_period_start', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('billing_period_end', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('projects_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('photos_uploaded_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('emails_sent_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('storage_used_bytes', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('last_recalculated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('developer_id', name=op.f('usage_counters_pkey'))
    )
    op.create_table('subscription_tier_limits',
    sa.Column('tier', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('max_units', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('monthly_fee_kes', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('max_projects', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_photos_per_upload', sa.INTEGER(), server_default=sa.text('20'), autoincrement=False, nullable=False),
    sa.Column('max_storage_gb', sa.INTEGER(), server_default=sa.text('50'), autoincrement=False, nullable=False),
    sa.Column('max_emails_per_month', sa.INTEGER(), server_default=sa.text('5000'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('tier', name=op.f('subscription_tier_limits_pkey'))
    )
    op.drop_index(op.f('ix_email_verification_codes_user_id'), table_name='email_verification_codes')
    op.drop_table('email_verification_codes')
    # ### end Alembic commands ###
