"""Add EmailVerificationCode

Revision ID: 7c981a79f455
Revises: 007
Create Date: 2026-06-16 13:43:46.584860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c981a79f455'
down_revision: Union[str, None] = '007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_codes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_codes_user_id'), 'email_verification_codes', ['user_id'], unique=False)
    op.drop_index(op.f('ix_developer_members_developer_id'), table_name='developer_members')
    op.drop_table('developer_members')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_user_role_assignments_developer_id'), table_name='user_role_assignments')
    op.drop_index(op.f('ix_user_role_assignments_user_id'), table_name='user_role_assignments')
    op.drop_table('user_role_assignments')
    op.drop_table('usage_counters')
    op.drop_index(op.f('ix_tenant_settings_developer_id'), table_name='tenant_settings')
    op.drop_table('tenant_settings')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_resource_action'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('subscription_tier_limits')
    op.drop_constraint(op.f('auth_token_deny_list_jti_key'), 'auth_token_deny_list', type_='unique')
    op.drop_index(op.f('ix_auth_token_deny_list_jti'), table_name='auth_token_deny_list')
    op.create_index(op.f('ix_auth_token_deny_list_jti'), 'auth_token_deny_list', ['jti'], unique=True)
    op.drop_constraint(op.f('buyers_project_id_fkey'), 'buyers', type_='foreignkey')
    op.drop_constraint(op.f('developers_user_id_key'), 'developers', type_='unique')
    op.drop_index(op.f('ix_developers_user_id'), table_name='developers')
    op.create_index(op.f('ix_developers_user_id'), 'developers', ['user_id'], unique=True)
    op.drop_constraint(op.f('developers_user_id_fkey'), 'developers', type_='foreignkey')
    op.drop_index(op.f('idx_inquiries_developer'), table_name='inquiries')
    op.drop_index(op.f('idx_inquiries_unseen'), table_name='inquiries', postgresql_where='(seen_by_developer = false)')
    op.drop_index(op.f('uq_inquiry_project_email'), table_name='inquiries')
    op.create_index(op.f('ix_inquiries_developer_id'), 'inquiries', ['developer_id'], unique=False)
    op.create_index(op.f('ix_inquiries_email'), 'inquiries', ['email'], unique=False)
    op.create_index(op.f('ix_inquiries_project_id'), 'inquiries', ['project_id'], unique=False)
    op.drop_index(op.f('ix_milestone_approvals_milestone'), table_name='milestone_approvals')
    op.drop_constraint(op.f('milestones_project_id_fkey'), 'milestones', type_='foreignkey')
    op.create_index(op.f('ix_notification_log_developer_id'), 'notification_log', ['developer_id'], unique=False)
    op.drop_constraint(op.f('password_reset_tokens_token_hash_key'), 'password_reset_tokens', type_='unique')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.drop_constraint(op.f('photos_upload_id_fkey'), 'photos', type_='foreignkey')
    op.drop_constraint(op.f('projects_project_code_key'), 'projects', type_='unique')
    op.drop_index(op.f('uq_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_code'), table_name='projects')
    op.create_index(op.f('ix_projects_project_code'), 'projects', ['project_code'], unique=True)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.drop_constraint(op.f('projects_developer_id_fkey'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('uploads_idempotency_key_key'), 'uploads', type_='unique')
    op.drop_index(op.f('ix_uploads_idempotency_key'), table_name='uploads')
    op.create_index(op.f('ix_uploads_idempotency_key'), 'uploads', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_uploads_milestone_id'), 'uploads', ['milestone_id'], unique=False)
    op.drop_constraint(op.f('uploads_developer_id_fkey'), 'uploads', type_='foreignkey')
    op.drop_constraint(op.f('uploads_project_id_fkey'), 'uploads', type_='foreignkey')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('idx_vpv_country'), table_name='visibility_page_views')
    op.drop_index(op.f('idx_vpv_project_time'), table_name='visibility_page_views')
    op.create_index(op.f('ix_visibility_page_views_project_id'), 'visibility_page_views', ['project_id'], unique=False)
    op.drop_constraint(op.f('webhook_events_event_id_key'), 'webhook_events', type_='unique')
    op.drop_index(op.f('ix_webhook_events_event_id'), table_name='webhook_events')
    op.create_index(op.f('ix_webhook_events_event_id'), 'webhook_events', ['event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_events_event_id'), table_name='webhook_events')
    op.create_index(op.f('ix_webhook_events_event_id'), 'webhook_events', ['event_id'], unique=False)
    op.create_unique_constraint(op.f('webhook_events_event_id_key'), 'webhook_events', ['event_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_visibility_page_views_project_id'), table_name='visibility_page_views')
    op.create_index(op.f('idx_vpv_project_time'), 'visibility_page_views', ['project_id', sa.literal_column('viewed_at DESC')], unique=False)
    op.create_index(op.f('idx_vpv_country'), 'visibility_page_views', ['project_id', 'country_code'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key(op.f('uploads_project_id_fkey'), 'uploads', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('uploads_developer_id_fkey'), 'uploads', 'developers', ['developer_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_uploads_milestone_id'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_idempotency_key'), table_name='uploads')
    op.create_index(op.f('ix_uploads_idempotency_key'), 'uploads', ['idempotency_key'], unique=False)
    op.create_unique_constraint(op.f('uploads_idempotency_key_key'), 'uploads', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key(op.f('projects_developer_id_fkey'), 'projects', 'developers', ['developer_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_code'), table_name='projects')
    op.create_index(op.f('ix_projects_project_code'), 'projects', ['project_code'], unique=False)
    op.create_index(op.f('uq_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_unique_constraint(op.f('projects_project_code_key'), 'projects', ['project_code'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key(op.f('photos_upload_id_fkey'), 'photos', 'uploads', ['upload_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=False)
    op.create_unique_constraint(op.f('password_reset_tokens_token_hash_key'), 'password_reset_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_notification_log_developer_id'), table_name='notification_log')
    op.create_foreign_key(op.f('milestones_project_id_fkey'), 'milestones', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_milestone_approvals_milestone'), 'milestone_approvals', ['milestone_id'], unique=False)
    op.drop_index(op.f('ix_inquiries_project_id'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_email'), table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_developer_id'), table_name='inquiries')
    op.create_index(op.f('uq_inquiry_project_email'), 'inquiries', ['project_id', 'email'], unique=True)
    op.create_index(op.f('idx_inquiries_unseen'), 'inquiries', ['project_id'], unique=False, postgresql_where='(seen_by_developer = false)')
    op.create_index(op.f('idx_inquiries_developer'), 'inquiries', ['developer_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_foreign_key(op.f('developers_user_id_fkey'), 'developers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_developers_user_id'), table_name='developers')
    op.create_index(op.f('ix_developers_user_id'), 'developers', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('developers_user_id_key'), 'developers', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key(op.f('buyers_project_id_fkey'), 'buyers', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_auth_token_deny_list_jti'), table_name='auth_token_deny_list')
    op.create_index(op.f('ix_auth_token_deny_list_jti'), 'auth_token_deny_list', ['jti'], unique=False)
    op.create_unique_constraint(op.f('auth_token_deny_list_jti_key'), 'auth_token_deny_list', ['jti'], postgresql_nulls_not_distinct=False)
    op.create_table('subscription_tier_limits',
    sa.Column('tier', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('max_units', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('monthly_fee_kes', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('max_projects', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_photos_per_upload', sa.INTEGER(), server_default=sa.text('20'), autoincrement=False, nullable=False),
    sa.Column('max_storage_gb', sa.INTEGER(), server_default=sa.text('50'), autoincrement=False, nullable=False),
    sa.Column('max_emails_per_month', sa.INTEGER(), server_default=sa.text('5000'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('tier', name=op.f('subscription_tier_limits_pkey'))
    )
    op.create_table('permissions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resource', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('permissions_pkey')),
    sa.UniqueConstraint('name', name=op.f('permissions_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_permissions_resource_action'), 'permissions', ['resource', 'action'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_system', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('roles_pkey')),
    sa.UniqueConstraint('name', name=op.f('roles_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('tenant_settings',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('developer_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], name=op.f('tenant_settings_developer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tenant_settings_pkey')),
    sa.UniqueConstraint('developer_id', 'key', name=op.f('uq_tenant_setting'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_tenant_settings_developer_id'), 'tenant_settings', ['developer_id'], unique=False)
    op.create_table('usage_counters',
    sa.Column('developer_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('billing_period_start', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('billing_period_end', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('projects_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('photos_uploaded_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('emails_sent_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('storage_used_bytes', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('last_recalculated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('developer_id', name=op.f('usage_counters_pkey'))
    )
    op.create_table('user_role_assignments',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('developer_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('granted_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('granted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('user_role_assignments_role_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_role_assignments_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_role_assignments_pkey')),
    sa.UniqueConstraint('user_id', 'role_id', 'developer_id', name=op.f('uq_user_role_dev'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_role_assignments_user_id'), 'user_role_assignments', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_role_assignments_developer_id'), 'user_role_assignments', ['developer_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('role_permissions_permission_id_fkey')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('role_permissions_role_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('role_permissions_pkey')),
    sa.UniqueConstraint('role_id', 'permission_id', name=op.f('uq_role_permissions'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('system_settings_pkey')),
    sa.UniqueConstraint('key', name=op.f('system_settings_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('developer_members',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('developer_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('org_role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('invited_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('invited_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('invitation_token', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('invitation_token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('invitation_status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('invited_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], name=op.f('developer_members_developer_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('developer_members_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('developer_members_pkey')),
    sa.UniqueConstraint('developer_id', 'user_id', name=op.f('uq_developer_member'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('invitation_token', name=op.f('developer_members_invitation_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_developer_members_developer_id'), 'developer_members', ['developer_id'], unique=False)
    op.drop_index(op.f('ix_email_verification_codes_user_id'), table_name='email_verification_codes')
    op.drop_table('email_verification_codes')
    # ### end Alembic commands ###
